### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [xgouchet/Chronorg#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by xgouchet** [comment]
Wow ! Ain't that a little bit of an invasive way to promote your framework ? Spamming all the github project you can find who use mockito-kotlin, with the same copy-pasted message ?

**Comment by oleksiyp** [comment]
I know it's a dark side. 

I took the risk because tried other ways and see it lacks targeting.

And here looks like targeting is OK:
~40 people said "thanks for letting me know" , 46 stars and 300 visits, and only a 3-4 said it's spam :smiley:

Happy Holidays :christmas_tree:  :christmas_tree:  :christmas_tree: :smiley:
